terms:
  - id: Article
    term: Article
  - id: Audio
    term: Audio
  - id: Book
    term: Book
  - id: Conference Proceeding
    term: Conference Proceeding
  - id: Data Set
    term: Data Set
  - id: Dissertation
    term: Dissertation
  - id: Image
    term: Image
  - id: Doctoral Thesis
    term: Doctoral Thesis
  - id: Masters Thesis
    term: Masters Thesis
  - id: Part of Book
    term: Part of Book
  - id: Poster
    term: Poster
  - id: Preprint
    term: Preprint
  - id: Postprint
    term: Postprint
  - id: Presentation
    term: Presentation
  - id: Research Paper
    term: Research Paper
  - id: Software or Program Code
    term: Software or Program Code
  - id: Technical Report
    term: Technical Report
  - id: Undergraduate Honors Thesis
    term: Undergraduate Honors Thesis
  - id: Undergraduate Thesis
    term: Undergraduate Thesis
  - id: Video
    term: Video
  - id: Working Paper
    term: Working Paper
  - id: Other
    term: Other
  - id: Brief
    term: Brief
  - id: Research Brief
    term: Research Brief
  - id: Policy Brief
    term: Policy Brief
  - id: Legislative Brief
    term: Legislative Brief
  - id: Memo
    term: Memo
  - id: Policy Memo
    term: Policy Memo
  - id: Review
    term : Review